### ISSUE TITLE
Maven beüzelemése

### ISSUE THREAD

**Issue by KZsolt11** [roBot92/portal_game#1]
A következő lépéseket hajtottam végre:
1. Beimportáltam a git projektet Eclipse-be
2. Konvertáltam az Eclipse-szel Maven projektté, ez létrehozta a pom.xml fájlt
3. A pom.xml-be beleírtam a függőségeket, amit használunk: junit, mock
4. mvn clean install

**Comment by roBot92** [comment]
Ellenőrizve
