### ISSUE TITLE
Travis beüzemelése

### ISSUE THREAD

**Issue by KZsolt11** [roBot92/portal_game#2]
travis.yml fájl tartalma:
language: java  
jdk:
- oraclejdk8   //jdk8-at használunk
cache:            //ezt elmentjük a cache-be
directories:
- $HOME/.m2

**Comment by roBot92** [comment]
pom.xml-re commit után travison fordult a projekt.

**Comment by roBot92** [comment]
Ellenőrizve

**Comment by miti01** [comment]
Ellenőriztem.
