### ISSUE TITLE
Statikus analízis eszköz futtatása és jelzett hibák javítása (SonarQube, FindBugs, VS Code Analyzer, Codacy, Coverity Scan)

### ISSUE THREAD

**Issue by roBot92** [roBot92/portal_game#4]
@Farkas25 re is írnám, csak nem fogadta el még a meghívást a projekthez.
Válasszatok egy eszközt légyszi, és futtassátok le, az alapján lehet javítgatni a hibákat.
A tárgyoldalon ki van emelve külön, hogy nem az összes hibát, mert elég érzékenyek ezek az eszközök.

**Comment by Farkas25** [comment]
Lefuttattam a SonarQube analízist a mvn sonar:sonar parancs segítségével. A keletkezett hibák: 27 bug, 7 vulnerability, 105 code smell. Ezek közül 1-1-et javítok ki.
